# Site settings
title: Bitcamp 2015
email: hello@bitca.mp
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://bitc.mp"
sponsors-partner: 
sponsors-corporate: [{"name": "Oculus VR", "logo": "img/sponsors/oculus.svg", "link": "https://www.oculus.com/"}]
sponsors-recruiter: [{"name": "TCS", "logo": "img/sponsors/tata.svg", "link": "http://www.tcs.com/Pages/default.aspx"},
 		      {"name": "The Washington Post", "logo": "img/sponsors/The_Washington_Post.svg", "link": "http://m.washingtonpost.com/"},
		     {"name": "LTS", "logo": "img/sponsors/lts.svg", "link": "http://www.ltsnet.net/"},
		     {"name": "Bloomberg", "logo": "img/sponsors/bloomberg.svg", "link": "http://www.bloomberg.com/"},
		     {"name": "Leidos", "logo": "img/sponsors/leidos.svg", "link": "https://www.leidos.com/"},
		     {"name": "Drakontas Consulting", "logo": "img/sponsors/Drakontas_Consulting.svg", "link": "http://drakontasconsulting.com/"},
		     {"name": "Capital One", "logo": "img/sponsors/Capital_One.svg", "link": "https://www.capitalone.com/"}]
sponsors-evangelist: [{"name": "Cipher Tech Solutions", "logo": "img/sponsors/cipher.svg", "link": "http://www.ciphertechsolutions.com/"},
 		      {"name": "Easy Dynamics", "logo": "img/sponsors/easydynamics.svg", "link": "http://www.easydynamics.com/"},
 		      {"name": "Strap", "logo": "img/sponsors/strap.svg", "link": "http://www.straphq.com/"},
 		      {"name": "Cisco", "logo": "img/sponsors/cisco.svg", "link": "http://www.cisco.com/"},
 		      {"name": "Facebook", "logo": "img/sponsors/Facebook.svg", "link": "https://www.facebook.com/"},
		      {"name": "OPIS", "logo": "img/sponsors/opis.svg", "link": "http://www.opisnet.com/"},
 		      {"name": "Thalmic Labs", "logo": "img/sponsors/thalmic.svg", "link": "https://www.thalmic.com/en/myo/"},
		      {"name": "ATT", "logo": "img/sponsors/att.svg", "link": "http://www.att.com/"},
		      {"name": "Pebble", "logo": "img/sponsors/Pebble.svg", "link": "http://www.pebble.com/"},
		      {"name": "Dealeron", "logo": "img/sponsors/dealeron_dark.svg", "link": "http://www.dealeron.com/"},
			  {"name": "Goldman Sachs", "logo": "img/sponsors/goldman.svg", "link": "http://www.goldmansachs.com/"}]
partners-1: [{"name": "Startup Shell", "logo": "img/partners/startup-shell.svg", "link": "https://www.startupshell.org/"},
			 {"name": "Terrapins Hackers", "logo": "img/partners/terrapin_hackers.svg", "link": "http://terrapinhackers.com/"}, 
		     {"name": "Major League Hacking", "logo": "img/partners/mlh.svg", "link": "https://www.mlh.io/"}, 
			 {"name": "Neelbauer Law", "logo": "img/partners/neelbauer.svg", "link": "http://www.neelbauerlaw.com/"}]
partners-2: [{"name": "College of Computer, Mathematical, & Natural Sciences", "logo": "img/partners/cmns.svg", "link": "https://cmns.umd.edu/"},
			 {"name": "University of Maryland Department of Computer Science", "logo": "img/partners/cs.svg", "link": "http://www.cs.umd.edu/"}, 
			 {"name": "University of Maryland Institute for Advanced Computer Studies", "logo": "img/partners/umiacs.svg", "link": "http://www.umiacs.umd.edu/"}]
